version: '3.8'

services:
  data_collector:
    build:
      context: .
      dockerfile: data/collection/Dockerfile
    volumes:
      - ./data:/data
      - ./config:/app/config
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
    networks:
      - utah_tta_network

  data_processor:
    build:
      context: .
      dockerfile: data/processing/Dockerfile
    volumes:
      - ./data:/data
    depends_on:
      - data_collector
    networks:
      - utah_tta_network

networks:
  utah_tta_network:
    driver: bridge 