name: utta
channels:
  - conda-forge
  - defaults
dependencies:
  # Python and core dependencies
  - python=3.10
  - pip
  
  # Scientific computing
  - numpy>=1.26.0
  - scipy>=1.10.1
  - scikit-learn>=1.3.0
  
  # Deep learning
  - pytorch>=2.0.0
  - faiss-gpu>=1.7.0
  
  # Data processing and visualization
  - pandas>=2.1.0
  - matplotlib>=3.8.0
  - plotly>=5.18.0
  - tqdm>=4.66.1
  
  # NLP and text processing
  - nltk>=3.8.1
  - gensim>=4.3.2
  
  # HTTP and networking
  - requests>=2.31.0
  
  - pip:
    # LLM and AI frameworks
    - dspy-ai>=2.3.9
    - openai>=1.3.0
    - anthropic>=0.5.0
    - langchain>=0.1.0
    - langchain-openai>=0.0.5
    - langchain-anthropic>=0.1.0
    - langchain-community>=0.0.16
    - langgraph>=0.0.20
    
    # Transformers and embeddings
    - sentence-transformers>=2.2.2
    - transformers>=4.34.0
    - bitsandbytes>=0.41.0
    - accelerate>=0.25.0
    - tiktoken>=0.5.1
    
    # Document processing
    - PyPDF2>=3.0.0
    - PyMuPDF>=1.18.14
    - python-docx>=0.8.11
    - beautifulsoup4>=4.11.1
    
    # Local model support
    - llama-cpp-python>=0.2.56
    - huggingface_hub>=0.20.3
    
    # Web and UI
    - streamlit>=1.30.0
    - wordcloud>=1.9.2
    
    # Database and storage
    - sqlite3-api>=0.1.0
    
    # Utilities
    - python-dotenv>=1.0.0
    - distro>=1.9.0
    - backoff>=2.2.1
    - colorama>=0.4.6
    - termcolor>=2.1.0
    - Pillow>=10.0.0
    - pydantic>=2.5.0
    
    # Development tools
    - black==24.1.1
    - isort==5.13.2
    - flake8==7.0.0
    - flake8-docstrings==1.7.0
    - mypy==1.8.0
    - pre-commit==3.6.0
    - pytest==8.0.0
    - pytest-cov==4.1.0 