name: utta
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3.1
  - pytorch=2.2.0
  - torchvision
  - numpy>=1.24.0
  - pandas>=2.0.0
  - pytest>=7.0.0
  - black>=23.0.0
  - flake8>=6.0.0
  - pip:
    - python-dotenv>=1.0.0
    - streamlit==1.32.0
    - textstat>=0.7.3
    - sentence-transformers==2.2.2
    - faiss-cpu>=1.7.4
    - spacy>=3.7.0
    - openai==0.28.0
    - dspy-ai==2.0.4
    - pytest-cov>=4.1.0
    - black>=23.0.0
    - flake8>=6.0.0
    - en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.0/en_core_web_sm-3.7.0-py3-none-any.whl
