name: utta
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.26.0
  - faiss-gpu>=1.7.0
  - requests>=2.31.0
  - tqdm>=4.66.1
  - scikit-learn>=1.3.0
  - matplotlib>=3.8.0
  - nltk>=3.8.1
  - pandas>=2.1.0
  - plotly>=5.18.0
  - gensim>=4.3.2
  - pytorch>=2.0.0
  - pip:
    - sentence-transformers>=2.2.2
    - wordcloud>=1.9.2
    - transformers>=4.34.0
    - bitsandbytes>=0.41.0
    - accelerate>=0.25.0
    - PyPDF2>=3.0.0
    - PyMuPDF>=1.18.14
    - python-docx>=0.8.11
    - beautifulsoup4>=4.11.1
    - colorama>=0.4.6
    - termcolor>=2.1.0
    - streamlit>=1.30.0
    # Development tools
    - black==24.1.1
    - isort==5.13.2
    - flake8==7.0.0
    - flake8-docstrings==1.7.0
    - mypy==1.8.0
    - pre-commit==3.6.0
    - pytest==8.0.0
    - pytest-cov==4.1.0 